# Generated by Django 5.1.4 on 2025-01-20 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.playlist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.song')),
            ],
        ),
    ]
