# Generated by Django 5.1.4 on 2025-01-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_playlistsong'),
    ]

    operations = [
        migrations.CreateModel(
            name='Karaoke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lyrics', models.TextField()),
                ('background_song', models.FileField(upload_to='karaoke_songs')),
                ('image', models.ImageField(upload_to='karaoke_images')),
            ],
        ),
    ]
