# Generated by Django 5.1.4 on 2025-01-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_karaoke'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='mood',
            field=models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('energetic', 'Energetic'), ('romantic', 'Romantic'), ('chill', 'Chill')], default='happy', max_length=100),
        ),
    ]
