# Generated by Django 5.1.4 on 2025-01-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_song_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karaoke',
            name='background_song',
            field=models.FileField(max_length=255, upload_to='karaoke_songs'),
        ),
    ]
