# Generated by Django 5.1.4 on 2025-01-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_karaoke_background_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karaoke',
            name='background_song',
            field=models.FileField(max_length=900, upload_to='karaoke_songs'),
        ),
    ]
